on:
  push:
    branches:
      - main
      - staging
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Running python build_file_list script
      run: python ./.github/workflows/build_file_list.py
    - name: Push changes
      run: |
        git config --global user.name AUTOMATION
        git config --global user.email "AUTOMATION@sudomagic.com"
        git status
        git add .
        git commit -m "Auto updating release manifests"
        git push